pub mod adapter_pattern;
pub mod bridge_pattern;
pub mod composite_pattern;
pub mod decorator_pattern;
pub mod facade_pattern;
pub mod filter_pattern;
pub mod flyweight_pattern;
pub mod proxy_pattern;
pub mod chain_of_responsibility_pattern;
